"$schema" = 'https://starship.rs/config-schema.json'

# プロンプト間に空行を入れる
add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 3
truncate_to_repo = true

[cmd_duration]
min_time = 2000
